### ISSUE TITLE
Conflict with starting DevServices if used with quarkus-oidc and Java 21

### ISSUE THREAD

**Issue by richardbischof** [microcks/microcks-quarkus#48] opened 2024-07-25 11:02 UTC
### Describe the bug

If microcks and oidc extensions are installed together, the content of two properties is overwritten
quarkus.oidc.auth-server-url=http://keycloak-j5knf:8080/realms/quarkus
keycloak.url=http://keycloak-j5knf:8080
This breaks the applications dev mode.

### Expected behavior

microcks and oidc extensions can be used together.

### How to Reproduce?

[Reproducer Repository](https://github.com/richardbischof/quarkus-microcks-oidc-reproducer)

### Microcks version or git rev

0.2.6

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

quarkus ext add microcks

**Comment by lbroudoux** [comment] 2024-07-26 10:08
Hello 👋 

I think this is related to the way the DevService container network is actually initialized (see https://github.com/quarkusio/quarkus/pull/39899). Are you using a Quarkus version >= 3.11 ?

Would you share a minimalistic Quarkus project so that I can try reproducing it?

**Comment by richardbischof** [comment] 2024-07-26 10:33
Hi, 

yes I'm using quarkus 3.12.3, see here: https://github.com/richardbischof/quarkus-microcks-oidc-reproducer

I tried it with quarkus 3.10.0 also, but the error still exists.

**Comment by lbroudoux** [comment] 2024-08-01 14:32
Thanks for the reproducer. I'm starting looking at it. I'll probably find some free cycles next week. I'll keep you posted.

**Comment by lbroudoux** [comment] 2024-08-01 15:17
Hey there!

Looks like I succeeded in making it start correctly by applying the same changes for database-related DevServices:

```
[INFO] Scanning for projects...
[INFO] 
[INFO] ---------------------------< org.acme:demo >----------------------------
[INFO] Building demo 1.0.0-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- quarkus:999-SNAPSHOT:dev (default-cli) @ demo ---
[INFO] Invoking resources:3.3.0:resources (default-resources) @ demo
[INFO] Copying 1 resource
[INFO] Invoking quarkus:999-SNAPSHOT:generate-code (default) @ demo
[INFO] Invoking compiler:3.13.0:compile (default-compile) @ demo
[INFO] Nothing to compile - all classes are up to date.
[INFO] Invoking resources:3.3.0:testResources (default-testResources) @ demo
[INFO] skip non existing resourceDirectory /Users/laurent/Development/github/quarkus-microcks-oidc-reproducer/src/test/resources
[INFO] Invoking quarkus:999-SNAPSHOT:generate-code-tests (default) @ demo
[INFO] Invoking compiler:3.13.0:testCompile (default-testCompile) @ demo
[INFO] Nothing to compile - all classes are up to date.
Listening for transport dt_socket at address: 5005
2024-08-01 17:15:24,304 INFO  [io.git.mic.qua.dep.DevServicesMicrocksProcessor] (build-2) The 'default' microcks container is ready on http://localhost:52771
2024-08-01 17:15:34,676 INFO  [io.qua.oid.dep.dev.key.KeycloakDevServicesProcessor] (build-9) Dev Services for Keycloak started.
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2024-08-01 17:15:35,009 WARN  [io.qua.config] (Quarkus Main Thread) Unrecognized configuration key "quarkus.microcks.default.grpc.host" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
2024-08-01 17:15:35,009 WARN  [io.qua.config] (Quarkus Main Thread) Unrecognized configuration key "quarkus.microcks.default.grpc" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
2024-08-01 17:15:35,009 WARN  [io.qua.config] (Quarkus Main Thread) Unrecognized configuration key "quarkus.microcks.default.http" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
2024-08-01 17:15:35,010 WARN  [io.qua.config] (Quarkus Main Thread) Unrecognized configuration key "quarkus.microcks.default.grpc.port" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
2024-08-01 17:15:35,010 WARN  [io.qua.config] (Quarkus Main Thread) Unrecognized configuration key "quarkus.devservices.microcks.service-name" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
2024-08-01 17:15:35,010 WARN  [io.qua.config] (Quarkus Main Thread) Unrecognized configuration key "quarkus.microcks.default.http.host" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
2024-08-01 17:15:35,010 WARN  [io.qua.config] (Quarkus Main Thread) Unrecognized configuration key "quarkus.microcks.default.http.port" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
2024-08-01 17:15:35,010 WARN  [io.qua.config] (Quarkus Main Thread) Unrecognized configuration key "quarkus.microcks.default.primary-artifacts" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
Microcks DevServices has been initialized
2024-08-01 17:15:35,310 INFO  [io.quarkus] (Quarkus Main Thread) demo 1.0.0-SNAPSHOT on JVM (powered by Quarkus 999-SNAPSHOT) started in 19.467s. Listening on: http://localhost:8080
2024-08-01 17:15:35,312 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2024-08-01 17:15:35,312 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [cdi, microcks, oidc, rest, security, smallrye-context-propagation, vertx]
2024-08-01 17:15:43,587 INFO  [io.quarkus] (Shutdown thread) demo stopped in 0.013s

--

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  31.889 s
[INFO] Finished at: 2024-08-01T17:15:44+02:00
[INFO] ------------------------------------------------------------------------
```

What may I check to be sure it is working as expected? Once validated, I may push my update on Quarkus upstream.

**Comment by richardbischof** [comment] 2024-08-02 06:45
Thank you for your quick response and your work. If I can do anything to support or double check, please let me know! :)

**Comment by lbroudoux** [comment] 2024-08-02 08:00
Aside the DevUI checks (for both Keycloak and Microcks DevServices) is there another way to validate via your app that the fix is working?

**Comment by lbroudoux** [comment] 2024-08-02 08:52
A fix in Quarkus has been submitted here: https://github.com/quarkusio/quarkus/pull/42288

**Comment by lbroudoux** [comment] 2024-08-02 12:45
PR has now been merged. We have to wait for the next Quarkus release. Keeping this open in the mean time.

**Comment by lbroudoux** [comment] 2024-08-20 12:50
Latest 3.13.1 version of Quarkus containing the bugfix resolves the reported issue

**Closed by lbroudoux** 2024-08-20 12:50 UTC
Labels: kind/question, component/runtime
