### ISSUE TITLE
quarkus.microcks.devservices.ensemble.* config not taken into account

### ISSUE THREAD

**Issue by rquinio1A** [microcks/microcks-quarkus#40] opened 2024-04-16 09:15 UTC
### Describe the bug

With Quarkus 3.2.10.Final-redhat-00003 and latest quarkus-microcks 0.2.3, it seems like the new configs listed in https://github.com/microcks/microcks-quarkus?tab=readme-ov-file#advanced-features-with-async-and-postman are not taken into account during `mvn quarkus:dev` mode.

Note that `%dev.quarkus.microcks.devservices.image-name` property is working well.

### Expected behavior

No warnings and ability to customize the async image name to go through a corporate registry.

### Actual behavior

I get the following warnings:

```
2024-04-16 11:03:01,304 WARN  [io.qua.config] (Quarkus Main Thread) Unrecognized configuration key "quarkus.microcks.devservices.ensemble.async-image-name" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
2024-04-16 11:03:01,305 WARN  [io.qua.config] (Quarkus Main Thread) Unrecognized configuration key "quarkus.microcks.devservices.ensemble.async-enabled" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
```

async is always enabled (even if there's no AsyncAPI primary artifact) and it uses the default async container image.

### How to Reproduce?

src/main/application.properties:

```properties
%dev.quarkus.microcks.devservices.ensemble.async-enabled=false
```

mvn quarkus:dev

### Microcks version or git rev

0.2.3

**Comment by lbroudoux** [comment] 2024-04-16 14:39
Hi @rquinio1A,
I think this is a duplicate of #38 that is fixed and will be embedded into the next release.

**Closed** 2024-04-16 14:39 UTC
Labels: status/duplicate
